### ISSUE TITLE
feature request: Can you add account remove.

### ISSUE THREAD

**Issue by parajbs** [s5-dev/S5#19]
Hello @redsolver,

A feature request:
The admin cannot delete an account at all.
Can you add account remove.

**Comment by redsolver** [comment]
should this delete all of the pins and uploaded files too? that might take a while

**Comment by redsolver** [comment]
added in https://github.com/s5-dev/S5/commit/013487fec45d30bd853417e878aa5470e79d29ea

**Comment by parajbs** [comment]
Hello **redsolver,**

Hello redsolver,

OK. I understand.

I wanted to delete an account (with email) so that you then have the option of creating a completely new account from the deleted account with the same email.

So technically, all pins and uploaded files should also be deleted.
But for my purpose it is not absolutely important.

**I think it should be enough for my concern to delete the email.**

And if it is later feasible that all pins and uploaded files will also be deleted.

**Comment by redsolver** [comment]
so the new implementation deletes the account, all pins, auth tokens and public keys. file objects are not deleted because that could be slow and other users might still be pinning them. I will file object deletion in the future. there's also a new delete account button in the admin web app ui
