### ISSUE TITLE
there are problems when building s5-node with rust 1.70.0

### ISSUE THREAD

**Issue by parajbs** [s5-dev/S5#20]
Hello @redsolver,

I just reinstalled one of my PCs, I noticed that "s5-node" doesn't work with the latest rust "1.70.x", there are errors with "cargo build --release".
And I couldn't start the s5-node.

I had to install rust "1.65.0" to avoid errors.
Now start the "s5-node" again.

**Comment by redsolver** [comment]
I just tried building the latest rust lib on a fresh Arch install, after setting up Rust 1.70.0 and installing Clang (https://wiki.archlinux.org/title/clang) it worked just fine. Which error message are you seeing?

**Comment by parajbs** [comment]
Hello @redsolver,

I'm not exactly sure what the error was.

I can still remember that the error message contained something with "ffi" and something with "bridge".

Since I recently had to reinstall a PC, I can try to install rust 1.70.x again there and reproduce the error.

I'll get back to you later

**Comment by parajbs** [comment]
Hello **@redsolver,**

Since the reinstallation of the PC about 2 weeks ago caused further problems, I had to reinstall the PC again with all the software.

**This all worked well.**

Now the installation from "s5-node" also works with the latest Rust "1.70.x" version.
There are no errors on cargo build --release.

sorry
**The iusse can be closed because everything works.**
