### ISSUE TITLE
Link directory to previous versions

### ISSUE THREAD

**Issue by pcfreak30** [s5-dev/S5#25]
A directory should have a means of storing the previous version on an update to enable a sort of `Windows defrag` so if app devs do not do things properly and assume they link the directory versions, you can track history and be able to unpin files and prevent them from cogging up any portal account.

**Comment by redsolver** [comment]
This is implemented in `DirectoryMetadata`, the `DirectoryMetadataDetails` map (which is basically a header) has an optional `previousVersion` field on `0x04`: https://github.com/s5-dev/lib5/blob/1ac7b21f6a35b489a0743ed522a33fab2d3c51a6/lib/src/model/metadata/directory.dart#L111
